const questions = [
  "What do you crave at the moment?",
  "Confess to something",
  "What would make you feel closer to me?",
  "What is one part of your body you are the most proud of?",
  "What musical artist is your secret guilty pleasure?",
  "What does my current phone wallpaper tell you about me?",
  "Do you think I intimidate others? Why?",
  "What is one misconception that people have about your professional occupation?",
  "What, in your opinion, is the hardest part of my job?",
  "Rate my dancing skills, on a scale of 1 to 10",
  "What does my instagram profile tell you about me?",
  "If you were to play in a band, what instrument would you choose to play?",
  "If you were a singer-songwriter, what genre would you play in?",
  "Name one movie that you watched multiple times",
  "If you were to pick a tattoo for me, what would it be and where would you place it?",
  "How did your sex drive change throughout your life, if at all",
  "What is your go-to category on pornography sites?",
  "Who did you want to be when you were a child?",
  "If money were not a problem and you had all the free time in the world, what would you do?",
  "What is your go-to comfort meal?",
  "If I were a desert, what would I be?",
  "What is your signature meal/recipe that you cook?",
  "What is your definition of success?",
  "Empathy or sympathy?",
  "If you had unlimited resources to start your own charity, what cause would you choose and why?",
  "What historical figure do you consider to be largely misunderstood?",
  "What is one thing that you've always wanted to try but never had a chance to?",
  "What is your definition of a good friendship?",
  "What does work-life balance look like to you?",
  "How do you perceive time - does time pass through you, or do you follow up after the movement of the time?",
  "If I had a badass street rap name, what would it be?",
  "What is one lfie lesson you learned that changed your life significantly?",
  "At this point in life, what is your spirit animal?",
  "If you were a clothing item, what would you be?",
  "If you need to evacuate your home immediately and you only have time to pick one thing with you. What would it be?",
  "If you had a time machine, would you go back in time or into the future?",
  "If you could have any superpower, what would it be and why?",
  "If you could describe your mood today with one emoji, which would it be?",
  "What would you like your safeword to be?",
  "What is your most sensitive body part?",
  "Team sport or individual performance?",
  "What is your favourite type of sport to watch and why?",
  "What does your favourite type of sport can teach the world?",
  "What does integrity mean to you?",
  "What is the most difficult moral dilemma you had to face in your life?",
  "Do you believe the ends always justify the means? Why or why not?",
  "What is the most difficult challenge facing our civilization as of today?",
  "What is the most difficult ethical challenge facing our society today?",
  "Who do you talk to first when you have a problem in a relationship?",
  "When someone talks to you about their problems, do you offer solutions or supportinve listening?",
  "What was your favourite subject at school?",
  "What was your least favourite subject at school?",
  "Reactiveness or structure?",
  "A small group of friends or a large community of acquaintances?",
  "What food do you crave at the moment?",
  "What are you more afraid of, failure or success?",
  "What has been your earliest recollection of happiness?",
  "What is a compliment you wish you received more frequently?",
  "What is a compliment you receive frequently that makes you uneasy?",
  "What about me is most strange or unfamiliar to you?",
  "How many speeding tickets do you think I've gotten and why?",
  "How many times in my life do you think I've been at a hospital?",
  "How likely am I to go camping? What makes you think so?",
  "Do I seem like a morning person or a night person?",
  "Do I seem like a cat or dog person?",
  "If I were a car, which one would I be?",
  "If you were to get me an exotic pet, which one would you get for me?",
  "As a child, what do you think I wanted to be?",
  "What's the best compliment a stranger has ever given you?",
  "What's your father's name? Tell me one thing about him.",
  "What title would you give this chapter in your life?",
  "What part of your life works? What part of your life hurts?",
  "What is something you would not want to change about yourself?",
  "Is there a feeling you miss?",
  "What is the first ever holiday you rememebr?",
  "What experience from your past do you think shaped you the most?",
  "Describe a moment when you felt most alive. What made it so special?",
  "What's a dream you've never shared with anyone? Why is it important to you?",
  "In what ways do you think we're similar, and how do we differ? Do these differences enhance our relationship?",
  "What's one fear you'd like to conquer? How can I support you in that?",
  "Share a memory from your childhood that brings you joy. Why does it stand out?",
  "If you could change one aspect of your life right now, what would it be and why?",
  "How do you prefer to be comforted when you're upset? Can you give an example?",
  "When you are upset, do you prefer to have someone to listen to you or to offer you solutions?",
  "When you see someone is upset, what do you think is more appropriate to listen or to offer solutions?",
  "What's a personal milestone you aim to achieve this year?",
  "What's something you've always wanted to do together with a partner?",
  "How do you define trust in a relationship?",
  "If and when you have a disagreement with your partner, who do you talk to first?",
  "What is the most valuable piece of advice you have ever received?",
  "Describe a tradition you'd like to start or continue within your family.",
  "Name one thing you admire about our relationship that you feel is unique to us.",
  "What's a challenge you've faced that you're proud of overcoming?",
  "What piece of art, like a book, a movie, or a show, that profoundly impacted your view of love or relationships.",
  "What's something you'd like us to do together that we haven't tried yet?",
  "How do you feel about the balance between our individual identities and our identity as a couple?",
  "What does a perfect day spent together look like to you?",
  "What is the type of communication channel (phone, text) that you prefer the most? Which one do you hate the most?",
  "How do you prefer to receive important or difficult information: through direct conversation, written messages, or another way? Why does this method make you feel most comfortable?",
  "Can you recall a time when you felt truly understood? What about that situation made you feel heard?",
  "What is your golden method to how you typically approach resolving the disagreement?",
  "In your opinion, what's the key to maintaining open and honest communication in a relationship?",
  "Share a situation where you found it hard to express your feelings. What do you think would have made it easier for you to communicate?",
  "What would our ideal lifestyle look like five years from now? What one step can we take today to make that vision a reality?",
  "If we could design our perfect home together, what unique features would it have, and why?",
  "Imagine we're planning a dream vacation that is symbolic of our relationship. Where would we go, and what activities would we do?",
  "What are some common goals we share that we can work towards together in the next year?",
  "When we think about retirement, what are the most important aspects for you? Is it travel, hobbies, community involvement, or something else?",
  "What's a valuable lesson you learned as a child that you'd like to pass on?",
  "Can you share a tradition from your family that you hold dear?",
  "What childhood activity made the biggest impact on you growing up?",
  "How did your family handle disagreements or conflicts when you were younger?",
  "Describe a moment when your family showed support for one another.",
  "What actor would play me in a movie, and why?",
  "What's a secret talent of yours that I haven't discovered yet?",
  "If you could pick any character from a book or movie to describe me, who would it be and why?",
  "What's the most spontaneous thing you've ever done in your life?",
  "If we were trapped alone, on a deserted island, what are three things you'd wish we had and why?",
  "What is the most romantic movie you've ever watched?",
  "What's something flirty you've wanted to say to me but haven't yet?",
  "What do standards mean to you?",
  "If you woke up one day, money and time were not a problem, how would you spend your days?",
  "If you could have all the time in the world, what would you study?",
  "You can only pick one - having your brain become a boundless AI, or having to spend all your life in a world without technology? ",
  "What is the most paranormal incident that ever happens to you?",
  "What paranormal phenomena do you believe are the closest to reality?",
  "What does the concept of a soul represent to you?",
  "On a scale of 1 to 10, how much risk are you ready to take in life?",
  "What is the funniest safe word you can come up with?",
  "What superpowers do you wish you had?",
  "What do you think is a real-life superpower that some people have?",
  "What superpower do you think suits me?",
  "What is the move you have watched an unhealthy amout of time?",
  "What do you consider the gravest crime of all time a human could do?",
  "As a child, who did you want to become when you grow up?",
  "Countryside or urban?",
  "Fight or walk away?",
  "If you are silent, is it a positive sign or a negative one?",
  "What is one thing in your life that has recently picked up a positive dynamic?",
  "Pick a side: soup, salad or fries?",
  "Tell me about your favourite toy when you were growing up?"
];

export default questions;